
[plugins]

gradleAndroidApplication = { id = "com.android.application", version.ref = "agp" }
gradleAndroidLibrary = { id = "com.android.library", version.ref = "agp" }
gradlePublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePublish" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
lbAndroidApplication = { id = "studio.lunabee.plugins.android.application", version.ref = "lbAndroidApplication" }
lbAndroidFlavors = { id = "studio.lunabee.plugins.android.flavors", version.ref = "lbAndroidFlavors" }
lbAndroidLibrary = { id = "studio.lunabee.plugins.android.library", version.ref = "lbAndroidLibrary" }
lbDetekt = { id = "studio.lunabee.plugins.detekt", version.ref = "lbDetekt" }
lbDokka = { id = "studio.lunabee.plugins.dokka", version.ref = "lbDokka" }
lbMultiplatformLibrary = { id = "studio.lunabee.plugins.multiplatform.library", version.ref = "lbMultiplatformLibrary" }
lbResources = { id = "studio.lunabee.plugins.resources", version.ref = "lbResources" }

[versions]

agp = "8.10.1"
androidxActivityCompose = "1.10.1"
androidxAppcompat = "1.7.0"
androidxComposeBom = "2025.05.01"
detekt = "1.23.8"
dokka = "2.0.0"
gradlePublish = "1.3.1"
kotlin = "2.1.21"
lbAndroidApplication = "1.0.0"
lbAndroidFlavors = "1.0.0"
lbAndroidLibrary = "1.0.0"
lbDetekt = "1.0.4"
lbDokka = "0.9.2"
lbMultiplatformLibrary = "0.9.1"
lbResources = "1.0.0"

[libraries]

androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
androidxAppCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidxComposeFoundation = { group = "androidx.compose.foundation", name = "foundation" }
androidxComposeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
dokkaGradlePlugin = { group = "org.jetbrains.dokka", name = "org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }
gradleAndroid = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
gradlePublishPlugin = { group = "com.gradle.plugin-publish", name = "com.gradle.plugin-publish.gradle.plugin", version.ref = "gradlePublish" }
kotlinCompose = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinMultiplatform = { group = "org.jetbrains.kotlin.multiplatform", name = "org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }
kotlinTest = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
