
[plugins]

gradleAndroidApplication = { id = "com.android.application", version.ref = "agp" }
gradleAndroidLibrary = { id = "com.android.library", version.ref = "agp" }
gradlePublish = { id = "com.gradle.plugin-publish", version.ref = "gradlePublish" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
lbAndroidApplication = { id = "studio.lunabee.plugin.android.application", version.ref = "lbAndroidApplication" }
lbAndroidFlavors = { id = "studio.lunabee.plugin.android.flavors", version.ref = "lbAndroidFlavors" }
lbAndroidLibrary = { id = "studio.lunabee.plugin.android.library", version.ref = "lbAndroidLibrary" }
lbDetekt = { id = "studio.lunabee.plugin.detekt", version.ref = "lbDetekt" }
lbDokka = { id = "studio.lunabee.plugin.dokka", version.ref = "lbDokka" }
lbMultiplatformAndroidLibrary = { id = "studio.lunabee.plugin.multiplatform.android.library", version.ref = "lbMultiplatformAndroidLibrary" }
lbMultiplatformLibrary = { id = "studio.lunabee.plugin.multiplatform.library", version.ref = "lbMultiplatformLibrary" }
lbResources = { id = "studio.lunabee.plugin.resources", version.ref = "lbResources" }

[versions]

agp = "9.0.0"
androidxActivityCompose = "1.12.2"
androidxAppcompat = "1.7.1"
androidxComposeBom = "2026.01.01"
detekt = "2.0.0-alpha.2"
dokka = "2.1.0"
gradlePublish = "2.0.0"
jreleaser = "1.22.0"
kotlin = "2.3.0"
lbAndroidApplication = "1.2.0"
lbAndroidFlavors = "1.2.0"
lbAndroidLibrary = "1.2.0"
lbDetekt = "2.0.6"
lbDokka = "1.0.0"
lbMultiplatformAndroidLibrary = "1.0.0"
lbMultiplatformLibrary = "2.0.0"
lbResources = "1.2.0"

[libraries]

androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityCompose" }
androidxAppCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidxComposeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidxComposeFoundation = { group = "androidx.compose.foundation", name = "foundation" }
androidxComposeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
detekt = { group = "dev.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
dokkaGradlePlugin = { group = "org.jetbrains.dokka", name = "org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }
gradleAndroid = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
gradlePublishPlugin = { group = "com.gradle.plugin-publish", name = "com.gradle.plugin-publish.gradle.plugin", version.ref = "gradlePublish" }
jreleaserGradlePlugin = { group = "org.jreleaser", name = "org.jreleaser.gradle.plugin", version.ref = "jreleaser" }
kotlinCompose = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlinGradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinMultiplatform = { group = "org.jetbrains.kotlin.multiplatform", name = "org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }
kotlinMultiplatformAndroid = { group = "com.android.kotlin.multiplatform.library", name = "com.android.kotlin.multiplatform.library.gradle.plugin", version.ref = "agp" }
kotlinTest = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
